kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "audit-dynamic-configuration": "true"
      "feature-gates=DynamicAuditing": "true"
      "runtime-config=auditregistration.k8s.io/v1alpha1": "true"
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /dev
    containerPath: /dev